apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-node
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kubernetes-node
  template:
    metadata:
      labels:
        app: kubernetes-node
    spec:
      containers:
        - name: node
          image: "{{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}"
          imagePullPolicy: {{ .Values.image.node.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: "kubernetes-postgres"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.auth.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
            - name: POSTGRES_DATABASE
              value: "{{ .Values.postgresql.auth.database }}"
            - name: POSTGRES_PG_DUMP_PATH
              value: "pg_dump"
            - name: POSTGRES_PORT
              value: "5432" # should be 5432 but it will crash the pod and it will always be restarting
            - name: JWTSECRET
              value: "jdsh09a8fh98adhfa9sduhfb9dag98u9SUHDU87867568sdfgzszdhfshf98ahf8h083t09ghjds98349hgbisogj09awnguiynifgjsd8bIOUGHSUDId089sghsub80"
            - name: JWTEXPIRATION
              value: "7d"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-nginx
  template:
    metadata:
      labels:
        app: kubernetes-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.nginx.targetPort }}
