apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubernetes-postgres
spec:
  serviceName: kubernetes-postgres
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-postgres
  template:
    metadata:
      labels:
        app: kubernetes-postgres
    spec:
      containers:
        - name: kubernetes-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: new-flux-api
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
